### PR TITLE
Add type 42 media parser

### PR DESCRIPTION
**Pull request by k-Dobosz**
Hi! I have added parser for type 42(media data). According to [this site](https://carlinkitcarplay.com/blogs/wireless-dongle-adapter/system-backend-settings) the sync mode should enable additional media data.

Data served by socket:
- MediaSongName, 
- MediaAlbumName, 
- MediaArtistName, 
- MediaAPPName, 
- MediaSongDuration, 
- MediaSongPlayTime, 
- MediaAlbumCover(base64)

### CODE REVIEW

**Comment by rhysmorgan134** [comment]
Thanks A lot! This looks awesome, I’ll have to get my Wi-Fi capable dongle out to change the sync mode (unsure how to do that on a non Wi-Fi dongle)

I suspect there is a configuration message that can be sent to the dongle via usb, I will try and figure that out.

Thanks again, I’ll review ASAP!

**Comment by k-Dobosz** [comment]
Great! For the reference I tested this on Carlinkit CPC200 with firmware version 2022.12.08.1636.

**Comment by rhysmorgan134** [comment]
Tested on my Wi-Fi model, all works well! Thanks a lot for this makes a lot of possibilities. Can I ask how you figured it out? Did you go through the apk? Or did you notice the 42 messages?

**Comment by k-Dobosz** [comment]
Actually, I found it by accident. I updated the dongle and then noticed the sync mode in the settings. I searched for what it does and read about the media data. After the update I opened my app and saw type 42 unknown messages appearing, so I realized that it might be the media data coming through, so I started playing out with it and yea, there it is.

**Pull request merged**
