### PR TITLE
Refactor messages, split files, add more message types from APK

### PR DESCRIPTION
**Pull request by gozmanyoni**
Adding 2 message types I saw and verified to work from de-compiled APK here - https://gist.github.com/harrylepotter/f4bfb37f11faf9efcfd6cd4b189cfa33

SendCloseDongle - will close dongle and require re-opening
SendDisconnectPhone. - will stop phone link but stay open, can re-connect without opening.

Supported a message called phase as well, with the initialisation phase, but no mapping of it yet.
When an unknown message is send - logging the payload as well to try and see what it is.

Lastly - splitting the messages.ts file to readable/sendable to reduce length and make these easier to read.

### CODE REVIEW

**Comment by rhysmorgan134** [comment]
Nice find on that file, quite handy. PR looks good to me. As an aside, feedback on the v4 react-carplay beta is unaminously positive around the performance compared to the old one!

**Comment by gozmanyoni** [comment]
@rhysmorgan134 that's amazing news! Still more improvements to be made :)

**Comment by rhysmorgan134** [comment]
@gozmanyoni One part I have noticed an issue with is when you stop feeding jmuxer frames, then resume, it will freeze until the next key frame. I have tried to request a keyframe via this function, however I am not 100% its going through properly. Do you think it's worth having a seperate method for this? If so should it sit in carplayWeb/carplayNode in your opinion? I am happy to look into implementing it, just wouldn't mind a steer if you have one.

**Comment by gozmanyoni** [comment]
@rhysmorgan134 looking at the implementation - it should go through correctly - you have added a case in the worker correctly - it doesn't log the line you have there?

I don't think we need a separate method as CarPlayWeb/Node exposes the driver with the send function - that is flexible enough to send all kinds of messages

**Comment by gozmanyoni** [comment]
@rhysmorgan134 also - we could just always keep rendering by removing the document.hidden check.

It might be very low load if hardware decoding + rendering is used without any muxing - https://github.com/rhysmorgan134/node-CarPlay/pull/67

I added that check when I was trying to optimise audio and before i introduced the ringbuffer base solution, may be an over optimisation.

**Comment by rhysmorgan134** [comment]
Yeah that makes sense, it did cross my mind to attempt keep feeding the frames, the time outside of carplay is minimal, so really not an issue, less so with that amazing pr!

**Pull request merged**
